//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class happyEntities : DbContext
    {
        public happyEntities()
            : base("name=happyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActivity> tActivities { get; set; }
        public virtual DbSet<tActivityMember> tActivityMembers { get; set; }
        public virtual DbSet<tAd> tAds { get; set; }
        public virtual DbSet<tCategory> tCategories { get; set; }
        public virtual DbSet<tChildcomment> tChildcomments { get; set; }
        public virtual DbSet<tFollow> tFollows { get; set; }
        public virtual DbSet<tFriendinvite> tFriendinvites { get; set; }
        public virtual DbSet<tGroup> tGroups { get; set; }
        public virtual DbSet<tGroupdetail> tGroupdetails { get; set; }
        public virtual DbSet<tManager> tManagers { get; set; }
        public virtual DbSet<tMember> tMembers { get; set; }
        public virtual DbSet<tMessage> tMessages { get; set; }
        public virtual DbSet<tNotify> tNotifies { get; set; }
        public virtual DbSet<tOrderdetail> tOrderdetails { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tParentcomment> tParentcomments { get; set; }
        public virtual DbSet<tPMSupplier> tPMSuppliers { get; set; }
        public virtual DbSet<tPost> tPosts { get; set; }
        public virtual DbSet<tPostliked> tPostlikeds { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tReport_Blog> tReport_Blog { get; set; }
        public virtual DbSet<tSupplier> tSuppliers { get; set; }
        public virtual DbSet<tTag> tTags { get; set; }
    }
}
