//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tActivity()
        {
            this.tActivityMembers = new HashSet<tActivityMember>();
        }
    
        public int fActivityId { get; set; }
        public int fCreatorId { get; set; }
        public Nullable<int> fGroupId { get; set; }
        public string fTitle { get; set; }
        public string fDescription { get; set; }
        public System.DateTime fCreatetime { get; set; }
        public System.DateTime fStarttime { get; set; }
        public System.DateTime fEndtime { get; set; }
    
        public virtual tGroup tGroup { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActivityMember> tActivityMembers { get; set; }
    }
}
