//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAd
    {
        public int fAdId { get; set; }
        public int fProductId { get; set; }
        public int fSupplierId { get; set; }
        public string fDescription { get; set; }
        public string fPicture { get; set; }
        public System.DateTime fStarttime { get; set; }
        public System.DateTime fEndtime { get; set; }
    
        public virtual tProduct tProduct { get; set; }
        public virtual tSupplier tSupplier { get; set; }
    }
}
