//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMessage
    {
        public int fMessageId { get; set; }
        public int fSenderId { get; set; }
        public int fReciverId { get; set; }
        public System.DateTime fDate { get; set; }
        public string fDescription { get; set; }
        public string fPicture { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tMember tMember1 { get; set; }
    }
}
