//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPost()
        {
            this.tParentcomments = new HashSet<tParentcomment>();
            this.tParentcomments1 = new HashSet<tParentcomment>();
            this.tPostlikeds = new HashSet<tPostliked>();
            this.tReport_Blog = new HashSet<tReport_Blog>();
            this.tMembers = new HashSet<tMember>();
            this.tTags = new HashSet<tTag>();
        }
    
        public int fPostId { get; set; }
        public int fMemberId { get; set; }
        public Nullable<int> fGroupId { get; set; }
        public string fTitle { get; set; }
        public string fDescription { get; set; }
        public System.DateTime fPosttime { get; set; }
        public Nullable<bool> fPersonal { get; set; }
        public Nullable<bool> fEarn { get; set; }
        public Nullable<bool> fHasImage { get; set; }
    
        public virtual tGroup tGroup { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tParentcomment> tParentcomments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tParentcomment> tParentcomments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPostliked> tPostlikeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReport_Blog> tReport_Blog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember> tMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTag> tTags { get; set; }
    }
}
