//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tAds = new HashSet<tAd>();
            this.tOrderdetails = new HashSet<tOrderdetail>();
            this.tPMSuppliers = new HashSet<tPMSupplier>();
        }
    
        public int fProductId { get; set; }
        public string fProductName { get; set; }
        public int fSupplierId { get; set; }
        public int fCategoryId { get; set; }
        public string fProductdescription { get; set; }
        public string fProductpicture { get; set; }
        public int fProductinstock { get; set; }
        public Nullable<int> fBrandId { get; set; }
        public int fUnitprice { get; set; }
        public string fProductsize { get; set; }
        public System.DateTime fProductlaunch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAd> tAds { get; set; }
        public virtual tCategory tCategory { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderdetail> tOrderdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPMSupplier> tPMSuppliers { get; set; }
        public virtual tSupplier tSupplier { get; set; }
    }
}
