//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnBlogAndShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSupplier()
        {
            this.tAds = new HashSet<tAd>();
            this.tProducts = new HashSet<tProduct>();
        }
    
        public int fSupplierId { get; set; }
        public Nullable<int> fMemberId { get; set; }
        public string fName { get; set; }
        public Nullable<bool> fStatus { get; set; }
        public Nullable<System.DateTime> fJointime { get; set; }
        public Nullable<decimal> fDiscount { get; set; }
        public Nullable<double> fGrade { get; set; }
        public string fDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAd> tAds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProduct> tProducts { get; set; }
    }
}
